<template>
    <BadashComponentStack    :back="windowHeight">
        <h1 class="display-1  text-center mt-4 mb-4">Stack of Technologies</h1>
        <div class="mt-5">
        <p class="pforward">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        <p class="pback">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        <p class="pforward">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        <p class="pback">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        <p class="pforward">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        <p class="pback">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        <p class="pforward">HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX  HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX HTML CSS JS VUE VUEX STYLED-COMPONENTS REACT REDUX REACT-REDUX AXIOS GIT REACT-THUNK SCSS PHOTOSHOP WEBSTORM AJAX </p>
        </div>
    </BadashComponentStack>
</template>
<script>
    import style from 'vue-styled-components'
    let back={
        back:Number
    }
    let BadashComponentStack = style('div',back)`
    overflow:hidden;
    height:${props => props.back}px;
    background-image: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    .display-1{
  font-size:50px;
  @media screen and (min-width: 900px) {
  font-size:100px;

  }
  }
    p{

    word-wrap: normal;
    display:flex;
    width:100%;
    margin:0;
    padding:0;
    font-family: 'Bebas Neue', cursive;
    font-size:40px;
    white-space:  nowrap ;
    }

  `
    export default {
        name:"Stack",
        components:{
            "BadashComponentStack":BadashComponentStack
        },
        data(){
            return{
                windowHeight:0
            }
        },
        created() {
            this.windowHeight = window.innerHeight
        }
    }
</script>
<style>

</style>